events{}

http{
	
	include mime.types;
	server{
		listen 8080;
		root /usr/share/nginx/html/example.com/;
		index index.html;

		error_page 404 /error.html;
		error_page 500 502 503 504 /error.html;
	}

	server{
		listen 80;
		root /usr/share/nginx/html/myexample.com/;
		index index.html;

		error_page 404 /error.html;
		error_page 500 502 503 504 /error.html;
	}
}
